const fs = require('fs');

const script = fs.readFileSync(
  '/Users/commander/Studio/consultala/wp-content/plugins/livecanvas-forge-ai/assets/studio-app.js',
  'utf8'
);
const admin = fs.readFileSync(
  '/Users/commander/Studio/consultala/wp-content/plugins/livecanvas-forge-ai/includes/class-lcfa-admin.php',
  'utf8'
);

const scriptTokens = [
  'wp.element',
  'wp.apiFetch',
  'lcfaStudio',
  'data-lcfa-studio-app-root',
  'fetchStudioJson',
  'fetchStudioState',
  'postStudioJson',
  'setFallbackHidden(true)',
  'setFallbackHidden(false)',
  'STORAGE_PREFIX',
  'useStoredState',
  'clearStoredViewPreferences',
  'AlertsPanel',
  'ContractPanel',
  'IntegrationTestPlanPanel',
  'HandoffReadinessPanel',
  'HandoffSummaryPanel',
  'ConnectionHandoffPanel',
  'OperatorBriefingPanel',
  'AgentSmokeTestsPanel',
  'AgentRunbookPanel',
  'BlockPatternLibraryPanel',
  'NativePatternPageBlueprintsPanel',
  'AgentHandoffPackagePanel',
  'RunHealthPanel',
  'AbilityManifestPanel',
  'AbilityExplorer',
  'WritePolicy',
  'InspectorPanel',
  'RunsExplorer',
  'runKey',
  'commandUrl',
  'sortAbilities',
  'sortRuns',
  'toggleColumn',
  'Sort abilities',
  'Sort runs',
  'data-lcfa-studio-column',
  'Copy name',
  'Copy audit',
  'Copy ability JSON',
  'Copy run JSON',
  'data-lcfa-studio-inspector',
  'Open Deck',
  'Refresh',
  'Reset view',
  'Copy Studio state',
  'Copy integration test plan',
  'Copy Codex smoke prompt',
  'Copy REST endpoint checklist',
  'Copy first preview request',
  'Copy contract',
  'Copy readiness',
  'Copy summary endpoint',
  'Copy handoff summary',
  'Copy handoff summary endpoint',
  'Copy endpoint response',
  'Copy endpoint parity',
  'Copy missing tests',
  'Copy write guards',
  'Refresh summary',
  'Refreshing summary...',
  'Copy first prompt',
  'Copy connection handoff',
  'Copy handoff endpoint',
  'data-lcfa-studio-contract',
  'data-lcfa-studio-integration-test-plan',
  'studio.integration-test-plan.v1',
  'data-lcfa-studio-handoff-readiness',
  'data-lcfa-studio-handoff-summary',
  'data-lcfa-studio-handoff-summary-refresh',
  'read_only_available',
  'preview_available',
  'write_guard_available',
  'unavailable_tests',
  'write_guard_tests',
  'next_action',
  'endpoint-error',
  'buildParity',
  'nestedValue',
  'compareValue',
  'Parity:',
  'Parity checks:',
  'parity-drift',
  'verified',
  'drift',
  'unverified',
  'studio_state',
  'data-lcfa-studio-connection-handoff',
  'Studio contract',
  'Integration test plan',
  'Handoff readiness',
  'Handoff summary',
  'Connection handoff',
  'Copy agent prompt',
  'Copy operator briefing',
  'Copy smoke tests',
  'guarded write checks',
  'Copy test payload',
  'Copy payload JSON',
  'Copy runbook markdown',
  'Copy agent runbook',
  'Copy block pattern library',
  'Copy pattern library endpoint',
  'Copy pattern content',
  'Copy pattern checksum',
  'Copy native page blueprints',
  'Copy blueprint endpoint',
  'Copy preview endpoint',
  'Copy apply endpoint',
  'Copy blueprint id',
  'Copy preview payload',
  'Copy preview request',
  'Copy apply request',
  'Run preview',
  'Running preview...',
  'Create draft page',
  'Creating draft...',
  'Copy apply result',
  'Copy audit ID',
  'Rollback draft',
  'Rollback ready',
  'onApplySuccess',
  'Draft created',
  'data-lcfa-studio-native-page-apply',
  'data-lcfa-studio-native-page-rollback',
  'Copy preview result',
  'Copy preview content',
  'data-lcfa-studio-native-page-preview',
  'Preview ready',
  'Preview failed',
  'Warnings:',
  'missing_pattern',
  'next-actions',
  'preview_request',
  'apply_request',
  'get_connection_handoff',
  'get_handoff_summary',
  'get_block_pattern_library',
  'get_native_pattern_page_blueprints',
  'preview_native_pattern_page',
  'apply_native_pattern_page',
  'apply-native-pattern-page',
  'Copy handoff package',
  'Copy package manifest',
  'Copy package endpoint',
  'Score:',
  'Missing tests:',
  'readiness_score',
  'Copy file',
  'Copy checksum',
  'data-lcfa-studio-agent-smoke-tests',
  'data-lcfa-studio-agent-runbook',
  'data-lcfa-studio-block-pattern-library',
  'data-lcfa-studio-native-pattern-page-blueprints',
  'data-lcfa-studio-handoff-package',
  'data-lcfa-studio-operator-briefing',
  'agent_smoke_tests',
  'agent_runbook',
  'block_pattern_library',
  'block_pattern_library_route',
  'native_pattern_page_blueprints',
  'native_pattern_page_blueprints_route',
  'native_pattern_page_preview_route',
  'native_pattern_page_apply_route',
  'agent_handoff_package',
  'connection_handoff',
  'handoff_summary',
  'handoff_summary_route',
  'connection_handoff_route',
  'handoff_package_route',
  'contract',
  'handoff_readiness',
  'operator_briefing',
  'Write guards',
  'Markdown handoff',
  'Agent handoff package',
  'Next actions',
  'Copy diagnostics',
  'Copy run analysis',
  'Copy ability manifest',
  'data-lcfa-studio-ability-manifest',
  'ability_manifest',
  'Input properties',
  'data-lcfa-studio-timeline',
  'run_analysis',
  'Action mix',
  'Origin mix',
  'data-lcfa-studio-alert',
  'generated_at',
  'createRoot',
];

for (const token of scriptTokens) {
  if (!script.includes(token)) {
    console.error(`studio-app.js should include ${token}`);
    process.exit(1);
  }
}

const adminTokens = [
  "'lcfa-studio-app'",
  "LCFA_URL . 'assets/studio-app.js'",
  "'wp-element'",
  "'wp-api-fetch'",
  "wp_localize_script('lcfa-studio-app'",
  'data-lcfa-studio-app-root',
  'data-lcfa-studio-fallback',
];

for (const token of adminTokens) {
  if (!admin.includes(token)) {
    console.error(`admin should enqueue/localize Studio React shell token ${token}`);
    process.exit(1);
  }
}

console.log('PASS');
